apiVersion: v2
name: qui-browser
description: A lightweight, secure web browser server with VR/WebXR support
type: application
version: 1.1.0
appVersion: "1.1.0"
keywords:
  - browser
  - webxr
  - vr
  - lightweight
  - secure
home: https://github.com/qui-browser/qui-browser
sources:
  - https://github.com/qui-browser/qui-browser
maintainers:
  - name: Qui Browser Team
    email: team@qui-browser.com
